package com.dongle.adx.dao.model;

import java.io.Serializable;
import java.util.Date;

public class TbCompany implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.person
     *
     * @mbg.generated
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.lisence
     *
     * @mbg.generated
     */
    private String lisence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.trade_type
     *
     * @mbg.generated
     */
    private Integer tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.op_user
     *
     * @mbg.generated
     */
    private String opUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.id
     *
     * @return the value of tb_company.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.id
     *
     * @param id the value for tb_company.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.name
     *
     * @return the value of tb_company.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.name
     *
     * @param name the value for tb_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.person
     *
     * @return the value of tb_company.person
     *
     * @mbg.generated
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.person
     *
     * @param person the value for tb_company.person
     *
     * @mbg.generated
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.tel
     *
     * @return the value of tb_company.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.tel
     *
     * @param tel the value for tb_company.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.email
     *
     * @return the value of tb_company.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.email
     *
     * @param email the value for tb_company.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.lisence
     *
     * @return the value of tb_company.lisence
     *
     * @mbg.generated
     */
    public String getLisence() {
        return lisence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.lisence
     *
     * @param lisence the value for tb_company.lisence
     *
     * @mbg.generated
     */
    public void setLisence(String lisence) {
        this.lisence = lisence == null ? null : lisence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.trade_type
     *
     * @return the value of tb_company.trade_type
     *
     * @mbg.generated
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.trade_type
     *
     * @param tradeType the value for tb_company.trade_type
     *
     * @mbg.generated
     */
    public void setTradeType(Integer tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.remark
     *
     * @return the value of tb_company.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.remark
     *
     * @param remark the value for tb_company.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.op_user
     *
     * @return the value of tb_company.op_user
     *
     * @mbg.generated
     */
    public String getOpUser() {
        return opUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.op_user
     *
     * @param opUser the value for tb_company.op_user
     *
     * @mbg.generated
     */
    public void setOpUser(String opUser) {
        this.opUser = opUser == null ? null : opUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.create_date
     *
     * @return the value of tb_company.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.create_date
     *
     * @param createDate the value for tb_company.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.update_date
     *
     * @return the value of tb_company.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.update_date
     *
     * @param updateDate the value for tb_company.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}