package com.dongle.adx.dao.model;

import java.io.Serializable;
import java.util.Date;

public class TbEntityDsp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.ident
     *
     * @mbg.generated
     */
    private String ident;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.adver_id
     *
     * @mbg.generated
     */
    private String adverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.plateform_id
     *
     * @mbg.generated
     */
    private String plateformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.land_url
     *
     * @mbg.generated
     */
    private String landUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.land_type
     *
     * @mbg.generated
     */
    private Integer landType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.img_url_1
     *
     * @mbg.generated
     */
    private String imgUrl1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.img_url_2
     *
     * @mbg.generated
     */
    private String imgUrl2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.img_url_3
     *
     * @mbg.generated
     */
    private String imgUrl3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.video_url
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.cover_url
     *
     * @mbg.generated
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.ad_type
     *
     * @mbg.generated
     */
    private Integer adType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.width
     *
     * @mbg.generated
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.trade_type
     *
     * @mbg.generated
     */
    private Integer tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.audit_status
     *
     * @mbg.generated
     */
    private String auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.audit_user
     *
     * @mbg.generated
     */
    private String auditUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.audit_msg
     *
     * @mbg.generated
     */
    private String auditMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.op_user
     *
     * @mbg.generated
     */
    private String opUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_entity_dsp.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_entity_dsp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.id
     *
     * @return the value of tb_entity_dsp.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.id
     *
     * @param id the value for tb_entity_dsp.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.name
     *
     * @return the value of tb_entity_dsp.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.name
     *
     * @param name the value for tb_entity_dsp.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.ident
     *
     * @return the value of tb_entity_dsp.ident
     *
     * @mbg.generated
     */
    public String getIdent() {
        return ident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.ident
     *
     * @param ident the value for tb_entity_dsp.ident
     *
     * @mbg.generated
     */
    public void setIdent(String ident) {
        this.ident = ident == null ? null : ident.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.adver_id
     *
     * @return the value of tb_entity_dsp.adver_id
     *
     * @mbg.generated
     */
    public String getAdverId() {
        return adverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.adver_id
     *
     * @param adverId the value for tb_entity_dsp.adver_id
     *
     * @mbg.generated
     */
    public void setAdverId(String adverId) {
        this.adverId = adverId == null ? null : adverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.plateform_id
     *
     * @return the value of tb_entity_dsp.plateform_id
     *
     * @mbg.generated
     */
    public String getPlateformId() {
        return plateformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.plateform_id
     *
     * @param plateformId the value for tb_entity_dsp.plateform_id
     *
     * @mbg.generated
     */
    public void setPlateformId(String plateformId) {
        this.plateformId = plateformId == null ? null : plateformId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.title
     *
     * @return the value of tb_entity_dsp.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.title
     *
     * @param title the value for tb_entity_dsp.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.content
     *
     * @return the value of tb_entity_dsp.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.content
     *
     * @param content the value for tb_entity_dsp.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.logo
     *
     * @return the value of tb_entity_dsp.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.logo
     *
     * @param logo the value for tb_entity_dsp.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.land_url
     *
     * @return the value of tb_entity_dsp.land_url
     *
     * @mbg.generated
     */
    public String getLandUrl() {
        return landUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.land_url
     *
     * @param landUrl the value for tb_entity_dsp.land_url
     *
     * @mbg.generated
     */
    public void setLandUrl(String landUrl) {
        this.landUrl = landUrl == null ? null : landUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.land_type
     *
     * @return the value of tb_entity_dsp.land_type
     *
     * @mbg.generated
     */
    public Integer getLandType() {
        return landType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.land_type
     *
     * @param landType the value for tb_entity_dsp.land_type
     *
     * @mbg.generated
     */
    public void setLandType(Integer landType) {
        this.landType = landType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.img_url_1
     *
     * @return the value of tb_entity_dsp.img_url_1
     *
     * @mbg.generated
     */
    public String getImgUrl1() {
        return imgUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.img_url_1
     *
     * @param imgUrl1 the value for tb_entity_dsp.img_url_1
     *
     * @mbg.generated
     */
    public void setImgUrl1(String imgUrl1) {
        this.imgUrl1 = imgUrl1 == null ? null : imgUrl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.img_url_2
     *
     * @return the value of tb_entity_dsp.img_url_2
     *
     * @mbg.generated
     */
    public String getImgUrl2() {
        return imgUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.img_url_2
     *
     * @param imgUrl2 the value for tb_entity_dsp.img_url_2
     *
     * @mbg.generated
     */
    public void setImgUrl2(String imgUrl2) {
        this.imgUrl2 = imgUrl2 == null ? null : imgUrl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.img_url_3
     *
     * @return the value of tb_entity_dsp.img_url_3
     *
     * @mbg.generated
     */
    public String getImgUrl3() {
        return imgUrl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.img_url_3
     *
     * @param imgUrl3 the value for tb_entity_dsp.img_url_3
     *
     * @mbg.generated
     */
    public void setImgUrl3(String imgUrl3) {
        this.imgUrl3 = imgUrl3 == null ? null : imgUrl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.video_url
     *
     * @return the value of tb_entity_dsp.video_url
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.video_url
     *
     * @param videoUrl the value for tb_entity_dsp.video_url
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.cover_url
     *
     * @return the value of tb_entity_dsp.cover_url
     *
     * @mbg.generated
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.cover_url
     *
     * @param coverUrl the value for tb_entity_dsp.cover_url
     *
     * @mbg.generated
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.duration
     *
     * @return the value of tb_entity_dsp.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.duration
     *
     * @param duration the value for tb_entity_dsp.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.ad_type
     *
     * @return the value of tb_entity_dsp.ad_type
     *
     * @mbg.generated
     */
    public Integer getAdType() {
        return adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.ad_type
     *
     * @param adType the value for tb_entity_dsp.ad_type
     *
     * @mbg.generated
     */
    public void setAdType(Integer adType) {
        this.adType = adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.width
     *
     * @return the value of tb_entity_dsp.width
     *
     * @mbg.generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.width
     *
     * @param width the value for tb_entity_dsp.width
     *
     * @mbg.generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.height
     *
     * @return the value of tb_entity_dsp.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.height
     *
     * @param height the value for tb_entity_dsp.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.trade_type
     *
     * @return the value of tb_entity_dsp.trade_type
     *
     * @mbg.generated
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.trade_type
     *
     * @param tradeType the value for tb_entity_dsp.trade_type
     *
     * @mbg.generated
     */
    public void setTradeType(Integer tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.audit_status
     *
     * @return the value of tb_entity_dsp.audit_status
     *
     * @mbg.generated
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.audit_status
     *
     * @param auditStatus the value for tb_entity_dsp.audit_status
     *
     * @mbg.generated
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.audit_user
     *
     * @return the value of tb_entity_dsp.audit_user
     *
     * @mbg.generated
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.audit_user
     *
     * @param auditUser the value for tb_entity_dsp.audit_user
     *
     * @mbg.generated
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser == null ? null : auditUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.audit_msg
     *
     * @return the value of tb_entity_dsp.audit_msg
     *
     * @mbg.generated
     */
    public String getAuditMsg() {
        return auditMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.audit_msg
     *
     * @param auditMsg the value for tb_entity_dsp.audit_msg
     *
     * @mbg.generated
     */
    public void setAuditMsg(String auditMsg) {
        this.auditMsg = auditMsg == null ? null : auditMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.status
     *
     * @return the value of tb_entity_dsp.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.status
     *
     * @param status the value for tb_entity_dsp.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.remark
     *
     * @return the value of tb_entity_dsp.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.remark
     *
     * @param remark the value for tb_entity_dsp.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.op_user
     *
     * @return the value of tb_entity_dsp.op_user
     *
     * @mbg.generated
     */
    public String getOpUser() {
        return opUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.op_user
     *
     * @param opUser the value for tb_entity_dsp.op_user
     *
     * @mbg.generated
     */
    public void setOpUser(String opUser) {
        this.opUser = opUser == null ? null : opUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.create_date
     *
     * @return the value of tb_entity_dsp.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.create_date
     *
     * @param createDate the value for tb_entity_dsp.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_entity_dsp.update_date
     *
     * @return the value of tb_entity_dsp.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_entity_dsp.update_date
     *
     * @param updateDate the value for tb_entity_dsp.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}