#server
server:
  port: 8079
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.iwanvi.nvwa.dao.model


logging:
  config: classpath:log4j.properties
#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/adx?characterEncodeing=utf8&autoReconnect=true
    username: root
    password: Dongle@123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 6
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 7
    timeout: 10s
    jedis:
      pool:
        max-active: 50
        max-wait: 30000ms
        max-idle: 10
        min-idle: 5
