package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.AdPositionTime;
import com.iwanvi.nvwa.dao.model.AdPositionTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdPositionTimeMapper {
    long countByExample(AdPositionTimeExample example);

    int deleteByExample(AdPositionTimeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AdPositionTime record);

    int insertSelective(AdPositionTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdPositionTime selectOneByExample(AdPositionTimeExample example);

    List<AdPositionTime> selectByExample(AdPositionTimeExample example);

    AdPositionTime selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") AdPositionTime record, @Param("example") AdPositionTimeExample example);

    int updateByExample(@Param("record") AdPositionTime record, @Param("example") AdPositionTimeExample example);

    int updateByPrimaryKeySelective(AdPositionTime record);

    int updateByPrimaryKey(AdPositionTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AdPositionTime> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AdPositionTime> list, @Param("selective") AdPositionTime.Column ... selective);
}