package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.AppChannel;
import com.iwanvi.nvwa.dao.model.AppChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppChannelMapper {
    long countByExample(AppChannelExample example);

    int deleteByExample(AppChannelExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AppChannel record);

    int insertSelective(AppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AppChannel selectOneByExample(AppChannelExample example);

    List<AppChannel> selectByExample(AppChannelExample example);

    AppChannel selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") AppChannel record, @Param("example") AppChannelExample example);

    int updateByExample(@Param("record") AppChannel record, @Param("example") AppChannelExample example);

    int updateByPrimaryKeySelective(AppChannel record);

    int updateByPrimaryKey(AppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AppChannel> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AppChannel> list, @Param("selective") AppChannel.Column ... selective);

	List<AppChannel> selectAppChannel();
	
	int selectByName(@Param("name") String channelname,@Param("cname") String cname);
}