package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.AppPkgBlacklist;
import com.iwanvi.nvwa.dao.model.AppPkgBlacklistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppPkgBlacklistMapper {
    long countByExample(AppPkgBlacklistExample example);

    int deleteByExample(AppPkgBlacklistExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AppPkgBlacklist record);

    int insertSelective(AppPkgBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_pkg_blacklist
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AppPkgBlacklist selectOneByExample(AppPkgBlacklistExample example);

    List<AppPkgBlacklist> selectByExample(AppPkgBlacklistExample example);

    AppPkgBlacklist selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") AppPkgBlacklist record, @Param("example") AppPkgBlacklistExample example);

    int updateByExample(@Param("record") AppPkgBlacklist record, @Param("example") AppPkgBlacklistExample example);

    int updateByPrimaryKeySelective(AppPkgBlacklist record);

    int updateByPrimaryKey(AppPkgBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_pkg_blacklist
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AppPkgBlacklist> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_pkg_blacklist
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AppPkgBlacklist> list, @Param("selective") AppPkgBlacklist.Column ... selective);
}