package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.Apps;
import com.iwanvi.nvwa.dao.model.AppsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppsMapper {
    long countByExample(AppsExample example);

    int deleteByExample(AppsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Apps record);

    int insertSelective(Apps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apps
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Apps selectOneByExample(AppsExample example);

    List<Apps> selectByExample(AppsExample example);

    Apps selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Apps record, @Param("example") AppsExample example);

    int updateByExample(@Param("record") Apps record, @Param("example") AppsExample example);

    int updateByPrimaryKeySelective(Apps record);

    int updateByPrimaryKey(Apps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apps
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Apps> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apps
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Apps> list, @Param("selective") Apps.Column ... selective);
}