package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.CompetingProducts;
import com.iwanvi.nvwa.dao.model.CompetingProductsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompetingProductsMapper {
    long countByExample(CompetingProductsExample example);

    int deleteByExample(CompetingProductsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CompetingProducts record);

    int insertSelective(CompetingProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competing_products
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CompetingProducts selectOneByExample(CompetingProductsExample example);

    List<CompetingProducts> selectByExample(CompetingProductsExample example);

    CompetingProducts selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") CompetingProducts record, @Param("example") CompetingProductsExample example);

    int updateByExample(@Param("record") CompetingProducts record, @Param("example") CompetingProductsExample example);

    int updateByPrimaryKeySelective(CompetingProducts record);

    int updateByPrimaryKey(CompetingProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competing_products
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CompetingProducts> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competing_products
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CompetingProducts> list, @Param("selective") CompetingProducts.Column ... selective);
}