package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.DspAdvertiser;
import com.iwanvi.nvwa.dao.model.DspAdvertiserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DspAdvertiserMapper {
    long countByExample(DspAdvertiserExample example);

    int deleteByExample(DspAdvertiserExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(DspAdvertiser record);

    int insertSelective(DspAdvertiser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DspAdvertiser selectOneByExample(DspAdvertiserExample example);

    List<DspAdvertiser> selectByExample(DspAdvertiserExample example);

    DspAdvertiser selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") DspAdvertiser record, @Param("example") DspAdvertiserExample example);

    int updateByExample(@Param("record") DspAdvertiser record, @Param("example") DspAdvertiserExample example);

    int updateByPrimaryKeySelective(DspAdvertiser record);

    int updateByPrimaryKey(DspAdvertiser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DspAdvertiser> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DspAdvertiser> list, @Param("selective") DspAdvertiser.Column ... selective);
}