package com.iwanvi.nvwa.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.iwanvi.nvwa.dao.model.Entity;
import com.iwanvi.nvwa.dao.model.EntityExample;

public interface EntityMapper {
    long countByExample(EntityExample example);

    int deleteByExample(EntityExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Entity record);

    int insertSelective(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Entity selectOneByExample(EntityExample example);

    List<Entity> selectByExample(EntityExample example);

    Entity selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Entity record, @Param("example") EntityExample example);

    int updateByExample(@Param("record") Entity record, @Param("example") EntityExample example);

    int updateByPrimaryKeySelective(Entity record);

    int updateByPrimaryKey(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Entity> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Entity> list, @Param("selective") Entity.Column ... selective);

    int selectCountForPage(@Param("entity") Entity entity, @Param("putType") Integer putType,
			@Param("putTypes") List<Integer> putTypes);

	List<Entity> selectForPage(@Param("entity") Entity entity, @Param("putType") Integer putType,
			@Param("putTypes") List<Integer> putTypes, @Param("start") int cp, @Param("limit") Integer ps);

	Map<String, Object> selectInfoWithOther(@Param("id") Integer id);

	int countListByMap(Map<String, Object> paramMap);

	List<Entity> listByMap(Map<String, Object> paramMap);

	Integer getAdsCnt();

	List<Map<String, Object>> getAdIds(Map<String, Object> paramMap);
}