package com.iwanvi.nvwa.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.iwanvi.nvwa.dao.model.EntityDsp;
import com.iwanvi.nvwa.dao.model.EntityDspExample;

public interface EntityDspMapper {
    long countByExample(EntityDspExample example);

    int deleteByExample(EntityDspExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(EntityDsp record);

    int insertSelective(EntityDsp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EntityDsp selectOneByExample(EntityDspExample example);

    List<EntityDsp> selectByExample(EntityDspExample example);

    EntityDsp selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") EntityDsp record, @Param("example") EntityDspExample example);

    int updateByExample(@Param("record") EntityDsp record, @Param("example") EntityDspExample example);

    int updateByPrimaryKeySelective(EntityDsp record);

    int updateByPrimaryKey(EntityDsp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<EntityDsp> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<EntityDsp> list, @Param("selective") EntityDsp.Column ... selective);
    
    Integer getAdsCnt();

    List<EntityDsp> getAdIds(Map<String, Object> paramMap);
}