package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.FlowControl;
import com.iwanvi.nvwa.dao.model.FlowControlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowControlMapper {
    long countByExample(FlowControlExample example);

    int deleteByExample(FlowControlExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(FlowControl record);

    int insertSelective(FlowControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_control
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FlowControl selectOneByExample(FlowControlExample example);

    List<FlowControl> selectByExample(FlowControlExample example);

    FlowControl selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") FlowControl record, @Param("example") FlowControlExample example);

    int updateByExample(@Param("record") FlowControl record, @Param("example") FlowControlExample example);

    int updateByPrimaryKeySelective(FlowControl record);

    int updateByPrimaryKey(FlowControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_control
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<FlowControl> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_control
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<FlowControl> list, @Param("selective") FlowControl.Column ... selective);
}