package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.FlowConsumer;
import com.iwanvi.nvwa.dao.model.FlowConsumerExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface FlowConsumerMapper {
    long countByExample(FlowConsumerExample example);

    int deleteByExample(FlowConsumerExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(FlowConsumer record);

    int insertSelective(FlowConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_consumer
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FlowConsumer selectOneByExample(FlowConsumerExample example);

    List<FlowConsumer> selectByExample(FlowConsumerExample example);

    FlowConsumer selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") FlowConsumer record, @Param("example") FlowConsumerExample example);

    int updateByExample(@Param("record") FlowConsumer record, @Param("example") FlowConsumerExample example);

    int updateByPrimaryKeySelective(FlowConsumer record);

    int updateByPrimaryKey(FlowConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_consumer
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<FlowConsumer> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_consumer
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<FlowConsumer> list, @Param("selective") FlowConsumer.Column ... selective);

	Integer getCnt();
	
	List<FlowConsumer> getIds(Map<String, Object> paramMap);
}