package com.iwanvi.nvwa.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.iwanvi.nvwa.dao.model.OrderPut;
import com.iwanvi.nvwa.dao.model.OrderPutExample;

public interface OrderPutMapper {
    long countByExample(OrderPutExample example);

    int deleteByExample(OrderPutExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(OrderPut record);

    int insertSelective(OrderPut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderPut selectOneByExample(OrderPutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderPut selectOneByExampleWithBLOBs(OrderPutExample example);

    List<OrderPut> selectByExampleWithBLOBs(OrderPutExample example);

    List<OrderPut> selectByExample(OrderPutExample example);

    OrderPut selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") OrderPut record, @Param("example") OrderPutExample example);

    int updateByExampleWithBLOBs(@Param("record") OrderPut record, @Param("example") OrderPutExample example);

    int updateByExample(@Param("record") OrderPut record, @Param("example") OrderPutExample example);

    int updateByPrimaryKeySelective(OrderPut record);

    int updateByPrimaryKeyWithBLOBs(OrderPut record);

    int updateByPrimaryKey(OrderPut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<OrderPut> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<OrderPut> list, @Param("selective") OrderPut.Column ... selective);

    int countByMap(Map<String, Object> paramMap);

	/**
	 * 
	 * @param putIds
	 * @return
	 */
	List<Map<String, Object>> getIdInfoByPutIds(Map<String, Object> paramMap);
}