package com.iwanvi.nvwa.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.iwanvi.nvwa.dao.model.Orders;
import com.iwanvi.nvwa.dao.model.OrdersExample;

public interface OrdersMapper {
	long countByExample(OrdersExample example);

	int deleteByExample(OrdersExample example);

	int deleteByPrimaryKey(Integer id);

	int insert(Orders record);

	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	Orders selectOneByExample(OrdersExample example);

	List<Orders> selectByExample(OrdersExample example);

	Orders selectByPrimaryKey(Integer id);

	int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

	int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

	int updateByPrimaryKeySelective(Orders record);

	int updateByPrimaryKey(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	int batchInsert(@Param("list") List<Orders> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	int batchInsertSelective(@Param("list") List<Orders> list, @Param("selective") Orders.Column... selective);

	List<Orders> selectForPage(@Param("order") Orders order, @Param("advers") List<Integer> advers,
			@Param("start") Integer start, @Param("limit") Integer limit);

	int countByMap(Map<String, Object> paramMap);
}