package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.OrderPutAll;
import com.iwanvi.nvwa.dao.model.OrderPutAllExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderPutAllMapper {
    long countByExample(OrderPutAllExample example);

    int deleteByExample(OrderPutAllExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(OrderPutAll record);

    int insertSelective(OrderPutAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderPutAll selectOneByExample(OrderPutAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderPutAll selectOneByExampleWithBLOBs(OrderPutAllExample example);

    List<OrderPutAll> selectByExampleWithBLOBs(OrderPutAllExample example);

    List<OrderPutAll> selectByExample(OrderPutAllExample example);

    OrderPutAll selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") OrderPutAll record, @Param("example") OrderPutAllExample example);

    int updateByExampleWithBLOBs(@Param("record") OrderPutAll record, @Param("example") OrderPutAllExample example);

    int updateByExample(@Param("record") OrderPutAll record, @Param("example") OrderPutAllExample example);

    int updateByPrimaryKeySelective(OrderPutAll record);

    int updateByPrimaryKeyWithBLOBs(OrderPutAll record);

    int updateByPrimaryKey(OrderPutAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<OrderPutAll> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_put_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<OrderPutAll> list, @Param("selective") OrderPutAll.Column ... selective);
}