package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.PutPositionTime;
import com.iwanvi.nvwa.dao.model.PutPositionTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PutPositionTimeMapper {
    long countByExample(PutPositionTimeExample example);

    int deleteByExample(PutPositionTimeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PutPositionTime record);

    int insertSelective(PutPositionTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table put_position_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PutPositionTime selectOneByExample(PutPositionTimeExample example);

    List<PutPositionTime> selectByExample(PutPositionTimeExample example);

    PutPositionTime selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") PutPositionTime record, @Param("example") PutPositionTimeExample example);

    int updateByExample(@Param("record") PutPositionTime record, @Param("example") PutPositionTimeExample example);

    int updateByPrimaryKeySelective(PutPositionTime record);

    int updateByPrimaryKey(PutPositionTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table put_position_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<PutPositionTime> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table put_position_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<PutPositionTime> list, @Param("selective") PutPositionTime.Column ... selective);
}