package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.QuotaFlowArea;
import com.iwanvi.nvwa.dao.model.QuotaFlowAreaExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface QuotaFlowAreaMapper {
    long countByExample(QuotaFlowAreaExample example);

    int deleteByExample(QuotaFlowAreaExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(QuotaFlowArea record);

    int insertSelective(QuotaFlowArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_flow_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    QuotaFlowArea selectOneByExample(QuotaFlowAreaExample example);

    List<QuotaFlowArea> selectByExample(QuotaFlowAreaExample example);

    QuotaFlowArea selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") QuotaFlowArea record, @Param("example") QuotaFlowAreaExample example);

    int updateByExample(@Param("record") QuotaFlowArea record, @Param("example") QuotaFlowAreaExample example);

    int updateByPrimaryKeySelective(QuotaFlowArea record);

    int updateByPrimaryKey(QuotaFlowArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_flow_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<QuotaFlowArea> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_flow_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<QuotaFlowArea> list, @Param("selective") QuotaFlowArea.Column ... selective);

    List<QuotaFlowArea> sumByDay(Map<String, Object> paramMap);

    List<QuotaFlowArea> detail(Map<String, Object> paramMap);

    QuotaFlowArea getQuotaFlowAreaByDay(int day);
}