package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.QuotaBook;
import com.iwanvi.nvwa.dao.model.QuotaBookExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface QuotaBookMapper {
    long countByExample(QuotaBookExample example);

    int deleteByExample(QuotaBookExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(QuotaBook record);

    int insertSelective(QuotaBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    QuotaBook selectOneByExample(QuotaBookExample example);

    List<QuotaBook> selectByExample(QuotaBookExample example);

    QuotaBook selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") QuotaBook record, @Param("example") QuotaBookExample example);

    int updateByExample(@Param("record") QuotaBook record, @Param("example") QuotaBookExample example);

    int updateByPrimaryKeySelective(QuotaBook record);

    int updateByPrimaryKey(QuotaBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<QuotaBook> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<QuotaBook> list, @Param("selective") QuotaBook.Column ... selective);

    List<QuotaBook> sumWithDate(Map<String, Object> paramMap);

    List<QuotaBook> sumWithGroup(Map<String, Object> paramMap);

    List<QuotaBook> detailReport(Map<String, Object> paramMap);
}