package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.SdkAllotSchedule;
import com.iwanvi.nvwa.dao.model.SdkAllotScheduleExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SdkAllotScheduleMapper {
    long countByExample(SdkAllotScheduleExample example);

    int deleteByExample(SdkAllotScheduleExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SdkAllotSchedule record);

    int insertSelective(SdkAllotSchedule record);

    List<SdkAllotSchedule> selectByExample(SdkAllotScheduleExample example);

    SdkAllotSchedule selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") SdkAllotSchedule record, @Param("example") SdkAllotScheduleExample example);

    int updateByExample(@Param("record") SdkAllotSchedule record, @Param("example") SdkAllotScheduleExample example);

    int updateByPrimaryKeySelective(SdkAllotSchedule record);

    int updateByPrimaryKey(SdkAllotSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_allot_schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    //SdkAllotSchedule selectOneByExample(SdkAllotScheduleExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_allot_schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SdkAllotSchedule> list);

    List<Map<String, Object>> getScheduleListByAllotmentId(Integer allotmentId);

    List<Map<String, Object>> getScheduleList(Map<String, Object> parMap);

    Long getScheduleCount();
    List<Map<String, Object>> getScheduleAll(Map<String, Object> parMap);
}