package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.SdkAllotment;
import com.iwanvi.nvwa.dao.model.SdkAllotmentExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SdkAllotmentMapper {
    long countByExample(SdkAllotmentExample example);

    int deleteByExample(SdkAllotmentExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SdkAllotment record);

    int insertSelective(SdkAllotment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_allotment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SdkAllotment selectOneByExample(SdkAllotmentExample example);

    List<SdkAllotment> selectByExample(SdkAllotmentExample example);

    SdkAllotment selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") SdkAllotment record, @Param("example") SdkAllotmentExample example);

    int updateByExample(@Param("record") SdkAllotment record, @Param("example") SdkAllotmentExample example);

    int updateByPrimaryKeySelective(SdkAllotment record);

    int updateByPrimaryKey(SdkAllotment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_allotment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SdkAllotment> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_allotment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SdkAllotment> list, @Param("selective") SdkAllotment.Column ... selective);

    List<Map<String, Object>> getAppList();
    
    List<Map<String, Object>> getPlatformList();

    List<Map<String, Object>> getAdPostionList(@Param("appId") Integer appId, @Param("platformId") Integer platformId);
}