package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.SdkAdCarousel;
import com.iwanvi.nvwa.dao.model.SdkAdCarouselExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SdkAdCarouselMapper {
    long countByExample(SdkAdCarouselExample example);

    int deleteByExample(SdkAdCarouselExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SdkAdCarousel record);

    int insertSelective(SdkAdCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_ad_carousel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SdkAdCarousel selectOneByExample(SdkAdCarouselExample example);

    List<SdkAdCarousel> selectByExample(SdkAdCarouselExample example);

    SdkAdCarousel selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") SdkAdCarousel record, @Param("example") SdkAdCarouselExample example);

    int updateByExample(@Param("record") SdkAdCarousel record, @Param("example") SdkAdCarouselExample example);

    int updateByPrimaryKeySelective(SdkAdCarousel record);

    int updateByPrimaryKey(SdkAdCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_ad_carousel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SdkAdCarousel> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_ad_carousel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SdkAdCarousel> list, @Param("selective") SdkAdCarousel.Column ... selective);
    
    List<Map<String, Object>> getAll(@Param("uuid")String uuid);

    List<Map<String, Object>> getByAppid(String appid);
}