package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.SdkReport;
import com.iwanvi.nvwa.dao.model.SdkReportExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SdkReportMapper {
    long countByExample(SdkReportExample example);

    int deleteByExample(SdkReportExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SdkReport record);

    int insertSelective(SdkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_report
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SdkReport selectOneByExample(SdkReportExample example);

    List<SdkReport> selectByExample(SdkReportExample example);

    SdkReport selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") SdkReport record, @Param("example") SdkReportExample example);

    int updateByExample(@Param("record") SdkReport record, @Param("example") SdkReportExample example);

    int updateByPrimaryKeySelective(SdkReport record);

    int updateByPrimaryKey(SdkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_report
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SdkReport> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_report
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SdkReport> list, @Param("selective") SdkReport.Column ... selective);

    List<SdkReport> sumReportWithDate(Map<String, Object> paramMap);

    List<SdkReport> sumReportWithGroup(Map<String, Object> paramMap);

    List<SdkReport> detailReport(Map<String, Object> paramMap);
}