package com.iwanvi.nvwa.dao;

import com.iwanvi.nvwa.dao.model.SettlementReport;
import com.iwanvi.nvwa.dao.model.SettlementReportExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SettlementReportMapper {
    long countByExample(SettlementReportExample example);

    int deleteByExample(SettlementReportExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SettlementReport record);

    int insertSelective(SettlementReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_report
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SettlementReport selectOneByExample(SettlementReportExample example);

    List<SettlementReport> selectByExample(SettlementReportExample example);

    SettlementReport selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") SettlementReport record, @Param("example") SettlementReportExample example);

    int updateByExample(@Param("record") SettlementReport record, @Param("example") SettlementReportExample example);

    int updateByPrimaryKeySelective(SettlementReport record);

    int updateByPrimaryKey(SettlementReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_report
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SettlementReport> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_report
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SettlementReport> list, @Param("selective") SettlementReport.Column ... selective);

    List<SettlementReport> sumReportWithDate(Map<String, Object> paramMap);

    List<SettlementReport> sumReportWithGroup(Map<String, Object> paramMap);

    List<SettlementReport> detailReport(Map<String, Object> paramMap);
}