server:
  port: 8081
spring:
  datasource:
    # driverClassName
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.dongle.com/dongle-question?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Dongle@123

mybatis:
  type-aliases-package: com.dongle.question.dao.entity
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml