#server
server:
  port: 8078
  
#log
logging: 
  config: classpath:log4j.properties

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.iwanvi.nvwa.dao.model

#spring
spring:
  datasource:
    url: jdbc:mysql://182.92.173.117:3306/zwww?useUnicode=true&amp;autoReconnect=true&amp;characterEncoding=UTF8
    username: test
    password: test@fftime
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 6
    
    
