#server
server:
  port: 8078
  
#log
logging: 
  config: classpath:log4j.properties

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.iwanvi.nvwa.dao.model

#spring
spring:
  datasource:
    url: jdbc:mysql://rm-2ze8m9018ujn2k1s3.mysql.rds.aliyuncs.com:3306/iwanvi?characterEncodeing=utf8&autoReconnect=true
    username: iwanvi_wr
    password: 2019@iwanvi_rds
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 6
    
    
