package com.iwanvi.nvwa.dao.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class AdPositionMapping {
    private Integer id;

    private Integer adPositionId;

    private Integer appId;

    private Integer flowConsumerId;

    private String consumerPositionId;

    private String consumerPositionName;

    private Integer width;

    private Integer height;

    private Double forecastRtbPrice;

    private Double forecastCtr;

    private Integer templateId;

    private Integer mapperType;

    private Double dspFloor;

    private Integer status;

    private Integer createUser;

    private Integer updateUser;

    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    private String consumerIds;

    private String positionIds;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAdPositionId() {
        return adPositionId;
    }

    public void setAdPositionId(Integer adPositionId) {
        this.adPositionId = adPositionId;
    }

    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public Integer getFlowConsumerId() {
        return flowConsumerId;
    }

    public void setFlowConsumerId(Integer flowConsumerId) {
        this.flowConsumerId = flowConsumerId;
    }

    public String getConsumerPositionId() {
        return consumerPositionId;
    }

    public void setConsumerPositionId(String consumerPositionId) {
        this.consumerPositionId = consumerPositionId;
    }

    public String getConsumerPositionName() {
        return consumerPositionName;
    }

    public void setConsumerPositionName(String consumerPositionName) {
        this.consumerPositionName = consumerPositionName;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Double getForecastRtbPrice() {
        return forecastRtbPrice;
    }

    public void setForecastRtbPrice(Double forecastRtbPrice) {
        this.forecastRtbPrice = forecastRtbPrice;
    }

    public Double getForecastCtr() {
        return forecastCtr;
    }

    public void setForecastCtr(Double forecastCtr) {
        this.forecastCtr = forecastCtr;
    }

    public Integer getTemplateId() {
        return templateId;
    }

    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    public Integer getMapperType() {
        return mapperType;
    }

    public void setMapperType(Integer mapperType) {
        this.mapperType = mapperType;
    }

    public Double getDspFloor() {
        return dspFloor;
    }

    public void setDspFloor(Double dspFloor) {
        this.dspFloor = dspFloor;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getCreateUser() {
        return createUser;
    }

    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    public Integer getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getConsumerIds() {
        return consumerIds;
    }

    public void setConsumerIds(String consumerIds) {
        this.consumerIds = consumerIds;
    }

    public String getPositionIds() {
        return positionIds;
    }

    public void setPositionIds(String positionIds) {
        this.positionIds = positionIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position_mapping
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static AdPositionMapping.Builder builder() {
        return new AdPositionMapping.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_position_mapping
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private AdPositionMapping obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new AdPositionMapping();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.id
         *
         * @param id the value for ad_position_mapping.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.ad_position_id
         *
         * @param adPositionId the value for ad_position_mapping.ad_position_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adPositionId(Integer adPositionId) {
            obj.setAdPositionId(adPositionId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.app_id
         *
         * @param appId the value for ad_position_mapping.app_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder appId(Integer appId) {
            obj.setAppId(appId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.flow_consumer_id
         *
         * @param flowConsumerId the value for ad_position_mapping.flow_consumer_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder flowConsumerId(Integer flowConsumerId) {
            obj.setFlowConsumerId(flowConsumerId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.consumer_position_id
         *
         * @param consumerPositionId the value for ad_position_mapping.consumer_position_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder consumerPositionId(String consumerPositionId) {
            obj.setConsumerPositionId(consumerPositionId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.consumer_position_name
         *
         * @param consumerPositionName the value for ad_position_mapping.consumer_position_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder consumerPositionName(String consumerPositionName) {
            obj.setConsumerPositionName(consumerPositionName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.width
         *
         * @param width the value for ad_position_mapping.width
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder width(Integer width) {
            obj.setWidth(width);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.height
         *
         * @param height the value for ad_position_mapping.height
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder height(Integer height) {
            obj.setHeight(height);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.forecast_RTB_price
         *
         * @param forecastRtbPrice the value for ad_position_mapping.forecast_RTB_price
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder forecastRtbPrice(Double forecastRtbPrice) {
            obj.setForecastRtbPrice(forecastRtbPrice);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.forecast_CTR
         *
         * @param forecastCtr the value for ad_position_mapping.forecast_CTR
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder forecastCtr(Double forecastCtr) {
            obj.setForecastCtr(forecastCtr);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.template_id
         *
         * @param templateId the value for ad_position_mapping.template_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder templateId(Integer templateId) {
            obj.setTemplateId(templateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.mapper_type
         *
         * @param mapperType the value for ad_position_mapping.mapper_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mapperType(Integer mapperType) {
            obj.setMapperType(mapperType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.dsp_floor
         *
         * @param dspFloor the value for ad_position_mapping.dsp_floor
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dspFloor(Double dspFloor) {
            obj.setDspFloor(dspFloor);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.status
         *
         * @param status the value for ad_position_mapping.status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder status(Integer status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.create_user
         *
         * @param createUser the value for ad_position_mapping.create_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createUser(Integer createUser) {
            obj.setCreateUser(createUser);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.update_user
         *
         * @param updateUser the value for ad_position_mapping.update_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateUser(Integer updateUser) {
            obj.setUpdateUser(updateUser);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.create_time
         *
         * @param createTime the value for ad_position_mapping.create_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column ad_position_mapping.update_time
         *
         * @param updateTime the value for ad_position_mapping.update_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public AdPositionMapping build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ad_position_mapping
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        adPositionId("ad_position_id", "adPositionId", "INTEGER", false),
        appId("app_id", "appId", "INTEGER", false),
        flowConsumerId("flow_consumer_id", "flowConsumerId", "INTEGER", false),
        consumerPositionId("consumer_position_id", "consumerPositionId", "VARCHAR", false),
        consumerPositionName("consumer_position_name", "consumerPositionName", "VARCHAR", false),
        width("width", "width", "INTEGER", false),
        height("height", "height", "INTEGER", false),
        forecastRtbPrice("forecast_RTB_price", "forecastRtbPrice", "DOUBLE", false),
        forecastCtr("forecast_CTR", "forecastCtr", "DOUBLE", false),
        templateId("template_id", "templateId", "INTEGER", false),
        mapperType("mapper_type", "mapperType", "INTEGER", false),
        dspFloor("dsp_floor", "dspFloor", "DOUBLE", false),
        status("status", "status", "INTEGER", false),
        createUser("create_user", "createUser", "INTEGER", false),
        updateUser("update_user", "updateUser", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ad_position_mapping
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}