package com.iwanvi.nvwa.dao.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class DspAdvertiser {
    private Integer id;

    private String name;

    private Integer flowConsumerId;

    private String dspAdvertiserId;

    private Integer status;

    private Integer examinesStatus;

    private Integer examinesUser;

    private Date examinesTime;

    private String examinesRemarks;

    private String businesslicense;

    private String qualifications;

    private Integer industryType;

    private String linkman;

    private String tel;

    private String address;

    private Date createTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getFlowConsumerId() {
        return flowConsumerId;
    }

    public void setFlowConsumerId(Integer flowConsumerId) {
        this.flowConsumerId = flowConsumerId;
    }

    public String getDspAdvertiserId() {
        return dspAdvertiserId;
    }

    public void setDspAdvertiserId(String dspAdvertiserId) {
        this.dspAdvertiserId = dspAdvertiserId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getExaminesStatus() {
        return examinesStatus;
    }

    public void setExaminesStatus(Integer examinesStatus) {
        this.examinesStatus = examinesStatus;
    }

    public Integer getExaminesUser() {
        return examinesUser;
    }

    public void setExaminesUser(Integer examinesUser) {
        this.examinesUser = examinesUser;
    }

    public Date getExaminesTime() {
        return examinesTime;
    }

    public void setExaminesTime(Date examinesTime) {
        this.examinesTime = examinesTime;
    }

    public String getExaminesRemarks() {
        return examinesRemarks;
    }

    public void setExaminesRemarks(String examinesRemarks) {
        this.examinesRemarks = examinesRemarks;
    }

    public String getBusinesslicense() {
        return businesslicense;
    }

    public void setBusinesslicense(String businesslicense) {
        this.businesslicense = businesslicense;
    }

    public String getQualifications() {
        return qualifications;
    }

    public void setQualifications(String qualifications) {
        this.qualifications = qualifications;
    }

    public Integer getIndustryType() {
        return industryType;
    }

    public void setIndustryType(Integer industryType) {
        this.industryType = industryType;
    }

    public String getLinkman() {
        return linkman;
    }

    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static DspAdvertiser.Builder builder() {
        return new DspAdvertiser.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table advertiser_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private DspAdvertiser obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new DspAdvertiser();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.id
         *
         * @param id the value for advertiser_dsp.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.name
         *
         * @param name the value for advertiser_dsp.name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.flow_consumer_id
         *
         * @param flowConsumerId the value for advertiser_dsp.flow_consumer_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder flowConsumerId(Integer flowConsumerId) {
            obj.setFlowConsumerId(flowConsumerId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.dsp_advertiser_id
         *
         * @param dspAdvertiserId the value for advertiser_dsp.dsp_advertiser_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dspAdvertiserId(String dspAdvertiserId) {
            obj.setDspAdvertiserId(dspAdvertiserId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.status
         *
         * @param status the value for advertiser_dsp.status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder status(Integer status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.examines_status
         *
         * @param examinesStatus the value for advertiser_dsp.examines_status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder examinesStatus(Integer examinesStatus) {
            obj.setExaminesStatus(examinesStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.examines_user
         *
         * @param examinesUser the value for advertiser_dsp.examines_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder examinesUser(Integer examinesUser) {
            obj.setExaminesUser(examinesUser);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.examines_time
         *
         * @param examinesTime the value for advertiser_dsp.examines_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder examinesTime(Date examinesTime) {
            obj.setExaminesTime(examinesTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.examines_remarks
         *
         * @param examinesRemarks the value for advertiser_dsp.examines_remarks
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder examinesRemarks(String examinesRemarks) {
            obj.setExaminesRemarks(examinesRemarks);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.businesslicense
         *
         * @param businesslicense the value for advertiser_dsp.businesslicense
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder businesslicense(String businesslicense) {
            obj.setBusinesslicense(businesslicense);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.qualifications
         *
         * @param qualifications the value for advertiser_dsp.qualifications
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qualifications(String qualifications) {
            obj.setQualifications(qualifications);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.industry_type
         *
         * @param industryType the value for advertiser_dsp.industry_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder industryType(Integer industryType) {
            obj.setIndustryType(industryType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.linkman
         *
         * @param linkman the value for advertiser_dsp.linkman
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder linkman(String linkman) {
            obj.setLinkman(linkman);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.tel
         *
         * @param tel the value for advertiser_dsp.tel
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tel(String tel) {
            obj.setTel(tel);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.address
         *
         * @param address the value for advertiser_dsp.address
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder address(String address) {
            obj.setAddress(address);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column advertiser_dsp.create_time
         *
         * @param createTime the value for advertiser_dsp.create_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DspAdvertiser build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table advertiser_dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", false),
        flowConsumerId("flow_consumer_id", "flowConsumerId", "INTEGER", false),
        dspAdvertiserId("dsp_advertiser_id", "dspAdvertiserId", "VARCHAR", false),
        status("status", "status", "INTEGER", false),
        examinesStatus("examines_status", "examinesStatus", "INTEGER", false),
        examinesUser("examines_user", "examinesUser", "INTEGER", false),
        examinesTime("examines_time", "examinesTime", "TIMESTAMP", false),
        examinesRemarks("examines_remarks", "examinesRemarks", "VARCHAR", false),
        businesslicense("businesslicense", "businesslicense", "VARCHAR", false),
        qualifications("qualifications", "qualifications", "VARCHAR", false),
        industryType("industry_type", "industryType", "INTEGER", false),
        linkman("linkman", "linkman", "VARCHAR", false),
        tel("tel", "tel", "VARCHAR", false),
        address("address", "address", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table advertiser_dsp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}