package com.iwanvi.nvwa.dao.model;


import java.util.ArrayList;
import java.util.Arrays;

public class QuotaFlowArea {
    private Integer id;

    private String area;

    private Integer creDay;

    private Long req = 0l;

    private Integer requv = 0;

    private Integer bid = 0;

    private Integer exp = 0;

    private Integer expuv = 0;

    private Integer clk = 0;

    private Integer clkuv = 0;

    private Long invest = 0l;

    private float investment = 0f;

    private float cpm = 0f;

    private float cpc = 0f;

    private double exp_rate;

    private double clk_rate;

    private Double expPer;

    private String areaName;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public Integer getCreDay() {
        return creDay;
    }

    public void setCreDay(Integer creDay) {
        this.creDay = creDay;
    }

    public Long getReq() {
        return req;
    }

    public void setReq(Long req) {
        this.req = req;
    }

    public Integer getRequv() {
        return requv;
    }

    public void setRequv(Integer requv) {
        this.requv = requv;
    }

    public Integer getBid() {
        return bid;
    }

    public void setBid(Integer bid) {
        this.bid = bid;
    }

    public Integer getExp() {
        return exp;
    }

    public void setExp(Integer exp) {
        this.exp = exp;
    }

    public Integer getExpuv() {
        return expuv;
    }

    public void setExpuv(Integer expuv) {
        this.expuv = expuv;
    }

    public Integer getClk() {
        return clk;
    }

    public void setClk(Integer clk) {
        this.clk = clk;
    }

    public Integer getClkuv() {
        return clkuv;
    }

    public void setClkuv(Integer clkuv) {
        this.clkuv = clkuv;
    }

    public Long getInvest() {
        return invest;
    }

    public void setInvest(Long invest) {
        this.invest = invest;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public float getCpm() {
        if (exp != null && exp != 0) {
            cpm = (float) getInvestment() / exp * 1000;
            cpm = (float) Math.round(cpm * 100) / 100;
        }
        return cpm;
    }

    public void setCpm(float cpm) {
        this.cpm = cpm;
    }

    public float getCpc() {
        if (clk != null && clk != 0) {
            cpc = (float) getInvestment() / clk;
            cpc = (float) Math.round(cpc * 100) / 100;
        }
        return cpc;
    }

    public void setCpc(float cpc) {
        this.cpc = cpc;
    }

    public double getExp_rate() {
        if (getReq() == null || getExp() == null) {
            exp_rate = 0 ;
        } else {
            if (getReq() > 0) {
                exp_rate = Double.parseDouble(String.format("%.2f", (((float)getExp() / (float)getReq()) * 100.0)));
            } else {
                exp_rate = 0;
            }
        }
        return exp_rate;
    }

    public double getClk_rate() {
        if (getClk() == null || getExp() == null) {
            clk_rate = 0;
        } else {
            if (getExp() > 0) {
                clk_rate = Double.parseDouble(String.format("%.2f", ((float)getClk() / (float)getExp()) * 100.0));
            } else {
                clk_rate = 0;
            }
        }
        return clk_rate;
    }

    public Double getExpPer() {
        if (getExpuv() == null || getExp() == null) {
            expPer = 0d;
        } else {
            if (getExpuv() > 0) {
                expPer = Double.parseDouble(String.format("%.2f", (((float)getExp() / (float)getExpuv()))));
            } else {
                expPer = 0d;
            }
        }
        return expPer;
    }

    public void setExpPer(Double expPer) {
        this.expPer = expPer;
    }

    public float getInvestment() {
        return (float) Math.round((float)invest / 1000) / 100;
    }

    public void setInvestment(float investment) {
        this.investment = investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_flow_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static QuotaFlowArea.Builder builder() {
        return new QuotaFlowArea.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quota_flow_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private QuotaFlowArea obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new QuotaFlowArea();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.id
         *
         * @param id the value for quota_flow_area.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.area
         *
         * @param area the value for quota_flow_area.area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder area(String area) {
            obj.setArea(area);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.cre_day
         *
         * @param creDay the value for quota_flow_area.cre_day
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder creDay(Integer creDay) {
            obj.setCreDay(creDay);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.req
         *
         * @param req the value for quota_flow_area.req
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder req(Long req) {
            obj.setReq(req);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.requv
         *
         * @param requv the value for quota_flow_area.requv
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder requv(Integer requv) {
            obj.setRequv(requv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.bid
         *
         * @param bid the value for quota_flow_area.bid
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bid(Integer bid) {
            obj.setBid(bid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.exp
         *
         * @param exp the value for quota_flow_area.exp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder exp(Integer exp) {
            obj.setExp(exp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.expuv
         *
         * @param expuv the value for quota_flow_area.expuv
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder expuv(Integer expuv) {
            obj.setExpuv(expuv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.clk
         *
         * @param clk the value for quota_flow_area.clk
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder clk(Integer clk) {
            obj.setClk(clk);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.clkuv
         *
         * @param clkuv the value for quota_flow_area.clkuv
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder clkuv(Integer clkuv) {
            obj.setClkuv(clkuv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column quota_flow_area.invest
         *
         * @param invest the value for quota_flow_area.invest
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder invest(Long invest) {
            obj.setInvest(invest);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public QuotaFlowArea build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table quota_flow_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        area("area", "area", "VARCHAR", false),
        creDay("cre_day", "creDay", "INTEGER", false),
        req("req", "req", "BIGINT", false),
        requv("requv", "requv", "INTEGER", false),
        bid("bid", "bid", "INTEGER", false),
        exp("exp", "exp", "INTEGER", false),
        expuv("expuv", "expuv", "INTEGER", false),
        clk("clk", "clk", "INTEGER", false),
        clkuv("clkuv", "clkuv", "INTEGER", false),
        invest("invest", "invest", "BIGINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_flow_area
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}