package com.iwanvi.nvwa.dao.model;

import java.util.ArrayList;
import java.util.List;

public class QuotaBookExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    public QuotaBookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public QuotaBookExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public QuotaBookExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public QuotaBookExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public QuotaBookExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public QuotaBookExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_book
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        QuotaBookExample example = new QuotaBookExample();
        return example.createCriteria();
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIdLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreDayIsNull() {
            addCriterion("cre_day is null");
            return (Criteria) this;
        }

        public Criteria andCreDayIsNotNull() {
            addCriterion("cre_day is not null");
            return (Criteria) this;
        }

        public Criteria andCreDayEqualTo(Integer value) {
            addCriterion("cre_day =", value, "creDay");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreDayEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("cre_day = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreDayNotEqualTo(Integer value) {
            addCriterion("cre_day <>", value, "creDay");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreDayNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("cre_day <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreDayGreaterThan(Integer value) {
            addCriterion("cre_day >", value, "creDay");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreDayGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("cre_day > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("cre_day >=", value, "creDay");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreDayGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("cre_day >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreDayLessThan(Integer value) {
            addCriterion("cre_day <", value, "creDay");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreDayLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("cre_day < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreDayLessThanOrEqualTo(Integer value) {
            addCriterion("cre_day <=", value, "creDay");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreDayLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("cre_day <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreDayIn(List<Integer> values) {
            addCriterion("cre_day in", values, "creDay");
            return (Criteria) this;
        }

        public Criteria andCreDayNotIn(List<Integer> values) {
            addCriterion("cre_day not in", values, "creDay");
            return (Criteria) this;
        }

        public Criteria andCreDayBetween(Integer value1, Integer value2) {
            addCriterion("cre_day between", value1, value2, "creDay");
            return (Criteria) this;
        }

        public Criteria andCreDayNotBetween(Integer value1, Integer value2) {
            addCriterion("cre_day not between", value1, value2, "creDay");
            return (Criteria) this;
        }

        public Criteria andLevel1IsNull() {
            addCriterion("level1 is null");
            return (Criteria) this;
        }

        public Criteria andLevel1IsNotNull() {
            addCriterion("level1 is not null");
            return (Criteria) this;
        }

        public Criteria andLevel1EqualTo(Integer value) {
            addCriterion("level1 =", value, "level1");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel1EqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level1 = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel1NotEqualTo(Integer value) {
            addCriterion("level1 <>", value, "level1");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel1NotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level1 <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel1GreaterThan(Integer value) {
            addCriterion("level1 >", value, "level1");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel1GreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level1 > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel1GreaterThanOrEqualTo(Integer value) {
            addCriterion("level1 >=", value, "level1");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel1GreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level1 >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel1LessThan(Integer value) {
            addCriterion("level1 <", value, "level1");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel1LessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level1 < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel1LessThanOrEqualTo(Integer value) {
            addCriterion("level1 <=", value, "level1");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel1LessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level1 <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel1In(List<Integer> values) {
            addCriterion("level1 in", values, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1NotIn(List<Integer> values) {
            addCriterion("level1 not in", values, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1Between(Integer value1, Integer value2) {
            addCriterion("level1 between", value1, value2, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1NotBetween(Integer value1, Integer value2) {
            addCriterion("level1 not between", value1, value2, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel2IsNull() {
            addCriterion("level2 is null");
            return (Criteria) this;
        }

        public Criteria andLevel2IsNotNull() {
            addCriterion("level2 is not null");
            return (Criteria) this;
        }

        public Criteria andLevel2EqualTo(Integer value) {
            addCriterion("level2 =", value, "level2");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel2EqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level2 = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel2NotEqualTo(Integer value) {
            addCriterion("level2 <>", value, "level2");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel2NotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level2 <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel2GreaterThan(Integer value) {
            addCriterion("level2 >", value, "level2");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel2GreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level2 > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel2GreaterThanOrEqualTo(Integer value) {
            addCriterion("level2 >=", value, "level2");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel2GreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level2 >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel2LessThan(Integer value) {
            addCriterion("level2 <", value, "level2");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel2LessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level2 < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel2LessThanOrEqualTo(Integer value) {
            addCriterion("level2 <=", value, "level2");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel2LessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level2 <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel2In(List<Integer> values) {
            addCriterion("level2 in", values, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2NotIn(List<Integer> values) {
            addCriterion("level2 not in", values, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2Between(Integer value1, Integer value2) {
            addCriterion("level2 between", value1, value2, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2NotBetween(Integer value1, Integer value2) {
            addCriterion("level2 not between", value1, value2, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel3IsNull() {
            addCriterion("level3 is null");
            return (Criteria) this;
        }

        public Criteria andLevel3IsNotNull() {
            addCriterion("level3 is not null");
            return (Criteria) this;
        }

        public Criteria andLevel3EqualTo(Integer value) {
            addCriterion("level3 =", value, "level3");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel3EqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level3 = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel3NotEqualTo(Integer value) {
            addCriterion("level3 <>", value, "level3");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel3NotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level3 <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel3GreaterThan(Integer value) {
            addCriterion("level3 >", value, "level3");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel3GreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level3 > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel3GreaterThanOrEqualTo(Integer value) {
            addCriterion("level3 >=", value, "level3");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel3GreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level3 >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel3LessThan(Integer value) {
            addCriterion("level3 <", value, "level3");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel3LessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level3 < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel3LessThanOrEqualTo(Integer value) {
            addCriterion("level3 <=", value, "level3");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLevel3LessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("level3 <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevel3In(List<Integer> values) {
            addCriterion("level3 in", values, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3NotIn(List<Integer> values) {
            addCriterion("level3 not in", values, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3Between(Integer value1, Integer value2) {
            addCriterion("level3 between", value1, value2, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3NotBetween(Integer value1, Integer value2) {
            addCriterion("level3 not between", value1, value2, "level3");
            return (Criteria) this;
        }

        public Criteria andReqIsNull() {
            addCriterion("req is null");
            return (Criteria) this;
        }

        public Criteria andReqIsNotNull() {
            addCriterion("req is not null");
            return (Criteria) this;
        }

        public Criteria andReqEqualTo(Integer value) {
            addCriterion("req =", value, "req");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReqEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("req = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andReqNotEqualTo(Integer value) {
            addCriterion("req <>", value, "req");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReqNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("req <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andReqGreaterThan(Integer value) {
            addCriterion("req >", value, "req");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReqGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("req > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andReqGreaterThanOrEqualTo(Integer value) {
            addCriterion("req >=", value, "req");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReqGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("req >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andReqLessThan(Integer value) {
            addCriterion("req <", value, "req");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReqLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("req < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andReqLessThanOrEqualTo(Integer value) {
            addCriterion("req <=", value, "req");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReqLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("req <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andReqIn(List<Integer> values) {
            addCriterion("req in", values, "req");
            return (Criteria) this;
        }

        public Criteria andReqNotIn(List<Integer> values) {
            addCriterion("req not in", values, "req");
            return (Criteria) this;
        }

        public Criteria andReqBetween(Integer value1, Integer value2) {
            addCriterion("req between", value1, value2, "req");
            return (Criteria) this;
        }

        public Criteria andReqNotBetween(Integer value1, Integer value2) {
            addCriterion("req not between", value1, value2, "req");
            return (Criteria) this;
        }

        public Criteria andRequvIsNull() {
            addCriterion("requv is null");
            return (Criteria) this;
        }

        public Criteria andRequvIsNotNull() {
            addCriterion("requv is not null");
            return (Criteria) this;
        }

        public Criteria andRequvEqualTo(Integer value) {
            addCriterion("requv =", value, "requv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRequvEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("requv = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRequvNotEqualTo(Integer value) {
            addCriterion("requv <>", value, "requv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRequvNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("requv <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRequvGreaterThan(Integer value) {
            addCriterion("requv >", value, "requv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRequvGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("requv > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRequvGreaterThanOrEqualTo(Integer value) {
            addCriterion("requv >=", value, "requv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRequvGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("requv >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRequvLessThan(Integer value) {
            addCriterion("requv <", value, "requv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRequvLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("requv < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRequvLessThanOrEqualTo(Integer value) {
            addCriterion("requv <=", value, "requv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRequvLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("requv <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRequvIn(List<Integer> values) {
            addCriterion("requv in", values, "requv");
            return (Criteria) this;
        }

        public Criteria andRequvNotIn(List<Integer> values) {
            addCriterion("requv not in", values, "requv");
            return (Criteria) this;
        }

        public Criteria andRequvBetween(Integer value1, Integer value2) {
            addCriterion("requv between", value1, value2, "requv");
            return (Criteria) this;
        }

        public Criteria andRequvNotBetween(Integer value1, Integer value2) {
            addCriterion("requv not between", value1, value2, "requv");
            return (Criteria) this;
        }

        public Criteria andExpIsNull() {
            addCriterion("exp is null");
            return (Criteria) this;
        }

        public Criteria andExpIsNotNull() {
            addCriterion("exp is not null");
            return (Criteria) this;
        }

        public Criteria andExpEqualTo(Integer value) {
            addCriterion("exp =", value, "exp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("exp = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpNotEqualTo(Integer value) {
            addCriterion("exp <>", value, "exp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("exp <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpGreaterThan(Integer value) {
            addCriterion("exp >", value, "exp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("exp > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpGreaterThanOrEqualTo(Integer value) {
            addCriterion("exp >=", value, "exp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("exp >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpLessThan(Integer value) {
            addCriterion("exp <", value, "exp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("exp < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpLessThanOrEqualTo(Integer value) {
            addCriterion("exp <=", value, "exp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("exp <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpIn(List<Integer> values) {
            addCriterion("exp in", values, "exp");
            return (Criteria) this;
        }

        public Criteria andExpNotIn(List<Integer> values) {
            addCriterion("exp not in", values, "exp");
            return (Criteria) this;
        }

        public Criteria andExpBetween(Integer value1, Integer value2) {
            addCriterion("exp between", value1, value2, "exp");
            return (Criteria) this;
        }

        public Criteria andExpNotBetween(Integer value1, Integer value2) {
            addCriterion("exp not between", value1, value2, "exp");
            return (Criteria) this;
        }

        public Criteria andExpuvIsNull() {
            addCriterion("expuv is null");
            return (Criteria) this;
        }

        public Criteria andExpuvIsNotNull() {
            addCriterion("expuv is not null");
            return (Criteria) this;
        }

        public Criteria andExpuvEqualTo(Integer value) {
            addCriterion("expuv =", value, "expuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpuvEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("expuv = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpuvNotEqualTo(Integer value) {
            addCriterion("expuv <>", value, "expuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpuvNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("expuv <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpuvGreaterThan(Integer value) {
            addCriterion("expuv >", value, "expuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpuvGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("expuv > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpuvGreaterThanOrEqualTo(Integer value) {
            addCriterion("expuv >=", value, "expuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpuvGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("expuv >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpuvLessThan(Integer value) {
            addCriterion("expuv <", value, "expuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpuvLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("expuv < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpuvLessThanOrEqualTo(Integer value) {
            addCriterion("expuv <=", value, "expuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpuvLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("expuv <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpuvIn(List<Integer> values) {
            addCriterion("expuv in", values, "expuv");
            return (Criteria) this;
        }

        public Criteria andExpuvNotIn(List<Integer> values) {
            addCriterion("expuv not in", values, "expuv");
            return (Criteria) this;
        }

        public Criteria andExpuvBetween(Integer value1, Integer value2) {
            addCriterion("expuv between", value1, value2, "expuv");
            return (Criteria) this;
        }

        public Criteria andExpuvNotBetween(Integer value1, Integer value2) {
            addCriterion("expuv not between", value1, value2, "expuv");
            return (Criteria) this;
        }

        public Criteria andClkIsNull() {
            addCriterion("clk is null");
            return (Criteria) this;
        }

        public Criteria andClkIsNotNull() {
            addCriterion("clk is not null");
            return (Criteria) this;
        }

        public Criteria andClkEqualTo(Integer value) {
            addCriterion("clk =", value, "clk");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clk = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkNotEqualTo(Integer value) {
            addCriterion("clk <>", value, "clk");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clk <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkGreaterThan(Integer value) {
            addCriterion("clk >", value, "clk");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clk > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkGreaterThanOrEqualTo(Integer value) {
            addCriterion("clk >=", value, "clk");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clk >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkLessThan(Integer value) {
            addCriterion("clk <", value, "clk");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clk < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkLessThanOrEqualTo(Integer value) {
            addCriterion("clk <=", value, "clk");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clk <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkIn(List<Integer> values) {
            addCriterion("clk in", values, "clk");
            return (Criteria) this;
        }

        public Criteria andClkNotIn(List<Integer> values) {
            addCriterion("clk not in", values, "clk");
            return (Criteria) this;
        }

        public Criteria andClkBetween(Integer value1, Integer value2) {
            addCriterion("clk between", value1, value2, "clk");
            return (Criteria) this;
        }

        public Criteria andClkNotBetween(Integer value1, Integer value2) {
            addCriterion("clk not between", value1, value2, "clk");
            return (Criteria) this;
        }

        public Criteria andClkuvIsNull() {
            addCriterion("clkuv is null");
            return (Criteria) this;
        }

        public Criteria andClkuvIsNotNull() {
            addCriterion("clkuv is not null");
            return (Criteria) this;
        }

        public Criteria andClkuvEqualTo(Integer value) {
            addCriterion("clkuv =", value, "clkuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkuvEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clkuv = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkuvNotEqualTo(Integer value) {
            addCriterion("clkuv <>", value, "clkuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkuvNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clkuv <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkuvGreaterThan(Integer value) {
            addCriterion("clkuv >", value, "clkuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkuvGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clkuv > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkuvGreaterThanOrEqualTo(Integer value) {
            addCriterion("clkuv >=", value, "clkuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkuvGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clkuv >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkuvLessThan(Integer value) {
            addCriterion("clkuv <", value, "clkuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkuvLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clkuv < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkuvLessThanOrEqualTo(Integer value) {
            addCriterion("clkuv <=", value, "clkuv");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClkuvLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("clkuv <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andClkuvIn(List<Integer> values) {
            addCriterion("clkuv in", values, "clkuv");
            return (Criteria) this;
        }

        public Criteria andClkuvNotIn(List<Integer> values) {
            addCriterion("clkuv not in", values, "clkuv");
            return (Criteria) this;
        }

        public Criteria andClkuvBetween(Integer value1, Integer value2) {
            addCriterion("clkuv between", value1, value2, "clkuv");
            return (Criteria) this;
        }

        public Criteria andClkuvNotBetween(Integer value1, Integer value2) {
            addCriterion("clkuv not between", value1, value2, "clkuv");
            return (Criteria) this;
        }

        public Criteria andInvestIsNull() {
            addCriterion("invest is null");
            return (Criteria) this;
        }

        public Criteria andInvestIsNotNull() {
            addCriterion("invest is not null");
            return (Criteria) this;
        }

        public Criteria andInvestEqualTo(Long value) {
            addCriterion("invest =", value, "invest");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andInvestEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("invest = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andInvestNotEqualTo(Long value) {
            addCriterion("invest <>", value, "invest");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andInvestNotEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("invest <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andInvestGreaterThan(Long value) {
            addCriterion("invest >", value, "invest");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andInvestGreaterThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("invest > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andInvestGreaterThanOrEqualTo(Long value) {
            addCriterion("invest >=", value, "invest");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andInvestGreaterThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("invest >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andInvestLessThan(Long value) {
            addCriterion("invest <", value, "invest");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andInvestLessThanColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("invest < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andInvestLessThanOrEqualTo(Long value) {
            addCriterion("invest <=", value, "invest");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andInvestLessThanOrEqualToColumn(QuotaBook.Column column) {
            addCriterion(new StringBuilder("invest <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andInvestIn(List<Long> values) {
            addCriterion("invest in", values, "invest");
            return (Criteria) this;
        }

        public Criteria andInvestNotIn(List<Long> values) {
            addCriterion("invest not in", values, "invest");
            return (Criteria) this;
        }

        public Criteria andInvestBetween(Long value1, Long value2) {
            addCriterion("invest between", value1, value2, "invest");
            return (Criteria) this;
        }

        public Criteria andInvestNotBetween(Long value1, Long value2) {
            addCriterion("invest not between", value1, value2, "invest");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private QuotaBookExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(QuotaBookExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public QuotaBookExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table quota_book
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table quota_book
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}