package com.iwanvi.nvwa.dao.model;

import java.util.ArrayList;
import java.util.Arrays;

public class WarningSetting {
    private Integer id;

    private Integer channelId;

    private Integer appId;

    private Integer pvTb;

    private Integer pvHb;

    private Integer clkTb;

    private Integer clkHb;

    private Integer pvTj;

    private Integer clkTj;

    private Integer status;

    private String email;

    private String channel_name;
    
    private String app_name;
    
    private Integer currentPage; 

    private Integer pageSize; 
    
    private String pv_hb_name;
    
    private String pv_tb_name;
    
    private String clk_hb_name;
    
    private String clk_tb_name;
    
    private String pv_tj_name;
    
    private String clk_tj_name;
    
    private Integer pv_one;
    
    private Integer pv_seven;
    
    private Integer clk_one;
    
    private Integer clk_seven;
    
    public Integer getPv_one() {
		return pv_one;
	}

	public void setPv_one(Integer pv_one) {
		this.pv_one = pv_one;
	}

	public Integer getPv_seven() {
		return pv_seven;
	}

	public void setPv_seven(Integer pv_seven) {
		this.pv_seven = pv_seven;
	}

	public Integer getClk_one() {
		return clk_one;
	}

	public void setClk_one(Integer clk_one) {
		this.clk_one = clk_one;
	}

	public Integer getClk_seven() {
		return clk_seven;
	}

	public void setClk_seven(Integer clk_seven) {
		this.clk_seven = clk_seven;
	}

	public String getPv_hb_name() {
		return pv_hb_name;
	}

	public void setPv_hb_name(String pv_hb_name) {
		this.pv_hb_name = pv_hb_name;
	}

	public String getPv_tb_name() {
		return pv_tb_name;
	}

	public void setPv_tb_name(String pv_tb_name) {
		this.pv_tb_name = pv_tb_name;
	}

	public String getClk_hb_name() {
		return clk_hb_name;
	}

	public void setClk_hb_name(String clk_hb_name) {
		this.clk_hb_name = clk_hb_name;
	}

	public String getClk_tb_name() {
		return clk_tb_name;
	}

	public void setClk_tb_name(String clk_tb_name) {
		this.clk_tb_name = clk_tb_name;
	}

	public String getPv_tj_name() {
		return pv_tj_name;
	}

	public void setPv_tj_name(String pv_tj_name) {
		this.pv_tj_name = pv_tj_name;
	}

	public String getClk_tj_name() {
		return clk_tj_name;
	}

	public void setClk_tj_name(String clk_tj_name) {
		this.clk_tj_name = clk_tj_name;
	}

	public Integer getCurrentPage() {
		return currentPage;
	}

	public void setCurrentPage(Integer currentPage) {
		this.currentPage = currentPage;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public String getChannel_name() {
		return channel_name;
	}

	public void setChannel_name(String channel_name) {
		this.channel_name = channel_name;
	}

	public String getApp_name() {
		return app_name;
	}

	public void setApp_name(String app_name) {
		this.app_name = app_name;
	}

	public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getChannelId() {
        return channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public Integer getPvTb() {
        return pvTb;
    }

    public void setPvTb(Integer pvTb) {
        this.pvTb = pvTb;
    }

    public Integer getPvHb() {
        return pvHb;
    }

    public void setPvHb(Integer pvHb) {
        this.pvHb = pvHb;
    }

    public Integer getClkTb() {
        return clkTb;
    }

    public void setClkTb(Integer clkTb) {
        this.clkTb = clkTb;
    }

    public Integer getClkHb() {
        return clkHb;
    }

    public void setClkHb(Integer clkHb) {
        this.clkHb = clkHb;
    }

    public Integer getPvTj() {
        return pvTj;
    }

    public void setPvTj(Integer pvTj) {
        this.pvTj = pvTj;
    }

    public Integer getClkTj() {
        return clkTj;
    }

    public void setClkTj(Integer clkTj) {
        this.clkTj = clkTj;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_setting
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static WarningSetting.Builder builder() {
        return new WarningSetting.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warning_setting
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private WarningSetting obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new WarningSetting();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.id
         *
         * @param id the value for warning_setting.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.channel_id
         *
         * @param channelId the value for warning_setting.channel_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder channelId(Integer channelId) {
            obj.setChannelId(channelId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.app_id
         *
         * @param appId the value for warning_setting.app_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder appId(Integer appId) {
            obj.setAppId(appId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.pv_tb
         *
         * @param pvTb the value for warning_setting.pv_tb
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pvTb(Integer pvTb) {
            obj.setPvTb(pvTb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.pv_hb
         *
         * @param pvHb the value for warning_setting.pv_hb
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pvHb(Integer pvHb) {
            obj.setPvHb(pvHb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.clk_tb
         *
         * @param clkTb the value for warning_setting.clk_tb
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder clkTb(Integer clkTb) {
            obj.setClkTb(clkTb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.clk_hb
         *
         * @param clkHb the value for warning_setting.clk_hb
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder clkHb(Integer clkHb) {
            obj.setClkHb(clkHb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.pv_tj
         *
         * @param pvTj the value for warning_setting.pv_tj
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pvTj(Integer pvTj) {
            obj.setPvTj(pvTj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.clk_tj
         *
         * @param clkTj the value for warning_setting.clk_tj
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder clkTj(Integer clkTj) {
            obj.setClkTj(clkTj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.status
         *
         * @param status the value for warning_setting.status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder status(Integer status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column warning_setting.email
         *
         * @param email the value for warning_setting.email
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder email(String email) {
            obj.setEmail(email);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public WarningSetting build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table warning_setting
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        channelId("channel_id", "channelId", "INTEGER", false),
        appId("app_id", "appId", "INTEGER", false),
        pvTb("pv_tb", "pvTb", "INTEGER", false),
        pvHb("pv_hb", "pvHb", "INTEGER", false),
        clkTb("clk_tb", "clkTb", "INTEGER", false),
        clkHb("clk_hb", "clkHb", "INTEGER", false),
        pvTj("pv_tj", "pvTj", "INTEGER", false),
        clkTj("clk_tj", "clkTj", "INTEGER", false),
        status("status", "status", "INTEGER", false),
        email("email", "email", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table warning_setting
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}